---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      version: '>=2.9.11'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: '>=25.8.2'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: '>=7.0.19'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            orgId: 1
            url: http://prometheus-server.monitoring.svc.cluster.local
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki-stack.monitoring.svc.cluster.local:3100
            isDefault: false
